### ISSUE TITLE
Can't reproduce the ideal performance as paper shown in Table 1

### ISSUE THREAD

**Issue by mashoujiang** [assafshocher/ZSSR#1]
Hi @assafshocher ,
Thanks for your great work and fancy idea in CVPR paper. I have a question when I try to reproduce your work. As title shown, I can not get the ideal performance results as Table 1 shown, which get 37.37/0.9570 for PSNR and SSIM. But I can only get about 34.91/0.9424. Please allow me to introduce the details of my training:
1. I can run your code smoothly by GPU thanks to your robust coding. 
2. To compare psnr and ssim, I firstly generate LR images by `scipy.misc.imresize()` (which is similar to matlab imresize I think.), then I can get the output SR images by configs.X2_GRADUAL_IDEAL_CONF and configs.X2_ONE_JUMP_IDEAL_CONF, both only get around 34dB PSNR. 
BTW, I noticed the training will stop when learning_rate < 1e-6, and at that time, the loop iterations only equals to around 1500.
I did not change code a lot, do I miss something?

**Comment by assafshocher** [comment]
Hi @mashoujiang ,
Thank a lot!
scipy.misc.imresize() is a bad choice. It does not return results like MATLAB at all.  for few reasons:
1. It does not use 'Antialiasing' feature.
2. If you use default settings, it uses linear interp rather than bicubic.
3. Even if you specify 'cubic', I think it is a different kernel than MATLAB's.
4. It is just not as accurate. I suspect that it suffers from a certain misalignment. It is actually deprecated.

You can either use MATLAB's, or even better- use [my resizer](https://github.com/assafshocher/Resizer)

Nevertheless, The gap you got is huge. So perhaps you changed something critical? or something went wrong in the evaluation?

Thanks for your comment!

**Comment by mashoujiang** [comment]
Hi @assafshocher ,
Thanks for your quick response! I will have a try as you suggested, good job!

**Comment by mashoujiang** [comment]
Hi @assafshocher , you right! I can get 36.96dB for dataset Set5 after using matlab imresize. Thanks a lot!
